package Models;

/**
 * holds and provides access to appointment data
 */
public class Appointment {

    private int appointmentID;
    private String title;
    private String description;
    private String location;
    private String type;
    private String start;
    private String end;
    private String createdBy;
    private String createDate;
    private String lastUpdate;
    private String lastUpdatedBy;
    private int customerID;
    private int userID;
    private int contactID;
    private String contact;


    /**
     * blank constructor for appointment
     */
    public Appointment(){}

    /**
     * constructor for appointment
     * @param appointmentID an ID for the appointment (auto generated by database)
     * @param title a title for the appointment
     * @param description a description for the appointment
     * @param location a location for the appointment
     * @param type the type of appointment
     * @param start the start date/time of the appointment
     * @param end the end date/time of the appointment
     * @param createdBy the user who created the appointment
     * @param createDate when the appointment was created
     * @param lastUpdate when the appointment was last updated
     * @param lastUpdatedBy who updated the last appointment
     * @param customerID the ID of the customer who the appointment belongs to
     * @param userID the userID of the user who created the appointment
     * @param contactID the contactId of the contact for the appointment.
     */
    public Appointment(int appointmentID, String title, String description, String location,
                            String type, String start, String end, String createdBy, String createDate,
                            String lastUpdate, String lastUpdatedBy, int customerID, int userID, int contactID) {
        this.appointmentID = appointmentID;
        this.title = title;
        this.description = description;
        this.location = location;
        this.type = type;
        this.start = start;
        this.end = end;
        this.createdBy = createdBy;
        this.createDate = createDate;
        this.lastUpdate = lastUpdate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.customerID = customerID;
        this.userID = userID;
        this.contactID = contactID;
    }

    /**
     * sets the appointment ID
     * @param appointmentID ID to be set
     */
    public void setAppointmentID(int appointmentID) {
        this.appointmentID = appointmentID;
    }

    /**
     * sets the contact
     * @param contact contact name to be set
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * sets the contactID
     * @param contactID the contactID to be set
     */
    public void setContactID(int contactID) {
        this.contactID = contactID;
    }

    /**
     * sets the date the appointment was created
     * @param createDate the date the appointment was created
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * sets the user that created the appointment
     * @param createdBy the name of the user
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * sets the customer Id of the customer tied to the appointment
     * @param customerID the Id of the customer
     */
    public void setCustomerID(int customerID) {
        this.customerID = customerID;
    }

    /**
     * sets the description of the appointment
     * @param description the description of the appointment
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * sets the end time of the appoint
     * @param end the end time of the appointment
     */
    public void setEnd(String end) {
        this.end = end;
    }

    /**
     * sets the time the appointment was last updated
     * @param lastUpdate the time the appointment was last updated
     */
    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * sets the user that last updated the appointment
     * @param lastUpdatedBy the username that last updated the appointment
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * sets the location of the appointment
     * @param location the location of the appointment
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * sets the start time of the appointment
     * @param start the start time of the appointment
     */
    public void setStart(String start) {
        this.start = start;
    }

    /**
     * sets the title of the appointment
     * @param title the title of the appointment
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * sets the type of the appointment
     * @param type the type of the appointment
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * sets the userID for the appointment
     * @param userID the userID for the appointment
     */
    public void setUserID(int userID) {
        this.userID = userID;
    }

    /**
     * retrieves the end time of the appointment
     * @return the end time of the appointment
     */
    public String getEnd() {
        return end;
    }

    /**
     * retrieves the userId of the appointment
     * @return the userId
     */
    public int getUserID() {
        return userID;
    }

    /**
     * retrieves the appointment ID of the appointment
     * @return the appointmentId
     */
    public int getAppointmentID() {
        return appointmentID;
    }

    /**
     * retrieves the contactId of the appointment
     * @return the appointmentID
     */
    public int getContactID() {
        return contactID;
    }

    /**
     * retrieves the customerID of the appointment
     * @return the customer ID
     */
    public int getCustomerID() {
        return customerID;
    }

    /**
     * retrieves the date the appointment was created
     * @return the date the appointment was created
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * retrieves the user who created the appointment
     * @return the user who created the appointment
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * retrieves the appointment description
     * @return the appointment description
     */
    public String getDescription() {
        return description;
    }

    /**
     * gets the time the appointment was last updated
     * @return the time the appointment was last updated
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /**
     * gets the user who last updated the appointment
     * @return the user who last updated the appointment
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * gets the location of the appointment
     * @return the location of the appointment
     */
    public String getLocation() {
        return location;
    }

    /**
     * gets the start time of the appointment
     * @return the start time of the appointment
     */
    public String getStart() {
        return start;
    }

    /**
     *gets the title of the appointment
     * @return the title of the appointment
     */
    public String getTitle() {
        return title;
    }

    /**
     * gets the type of appointment
     * @return the appointment type
     */
    public String getType() {
        return type;
    }

    /**
     * gets the contact for the appointment
     * @return the contact
     */
    public String getContact() {
        return contact;
    }
}
